### ISSUE TITLE
Passive Perception Score is wrong

### ISSUE THREAD

**Issue by jopeek** [jopeek/fvtt-token-info-icons#1]
@Ithiloneth   The Passive Perception in the module Token Info Icons seems to be based on Active Perception score.
If I give a character an effect which increases Passive Perception using Dynamic Effects the change is shown on the character sheet, but not on the HUD.

**Comment by arkaris** [comment]
D&D 5e passive persaption equals wisdom mod + perseption skill modifier.
This module doesn't know it.
