### ISSUE TITLE
Speed is broken for new tokens

### ISSUE THREAD

**Issue by tobloef** [jopeek/fvtt-token-info-icons#13]
I think a recent version of foundry may have deprecated the `speed` attribute. Now there are multiple speeds (walk, fly burrow, etc.), under the `movement` attribute. This means that the speed shows up as empty on new tokens. I don't know the plans for the module, but if you don't want to add some UI to select which speed to use, just using `movement.walk` would probably be a fine fix for now.

**Comment by jopeek** [comment]
Fixed in 2.1.0
