### ISSUE TITLE
Not working after most recent D&D update

### ISSUE THREAD

**Issue by Avitale34** [jopeek/fvtt-token-info-icons#20]
It seems like the newest update has caused an issue with this module :(

**Comment by jopeek** [comment]
Always fun! I’ll try to fix it today or tomorrow.

**Comment by jopeek** [comment]
Got a screenshot? It looks fine to me.

**Comment by Avitale34** [comment]
![image](https://user-images.githubusercontent.com/65961637/103954168-a33e6000-5111-11eb-9fc8-290320fa4a26.png)

**Comment by Avitale34** [comment]
I don't even see it in my module settings. It is checked off in my manage modules though.

**Comment by jopeek** [comment]
I upgraded to dnd5e 1.2.2 and in a world with no other modules enabled, things work well. Can you doublecheck yours and try disabling other modules?

**Comment by zacdemon** [comment]
I'm also experiencing this issue, after some testing I've found that the conflcit is with the module Active Auras. While the module is active token info icons wont display on the module settings list.

**Comment by kandashi** [comment]
This has been fixed on the side of Active Auras, @jopeek ive dropped an issue #21  to suggest a way of less conflicts arrising 👍

**Comment by jopeek** [comment]
Thank you, will implement it with the next release.

**Comment by jopeek** [comment]
Fixed in 2.2.1
