### ISSUE TITLE
Token Info 2.3.2 Stopped Working in 0.7.10

### ISSUE THREAD

**Issue by Jacao009** [jopeek/fvtt-token-info-icons#27]
Token Info 2.3.2 stopped working in 0.7.10. I'm using the Game Manager/Bazaar of The Forge. 2 days ago it was working fine.

**Comment by jopeek** [comment]
The latest is no longer compatible with 0.7.x. Try manually installing this version: https://github.com/jopeek/fvtt-token-info-icons/releases/tag/2.3.0

**Comment by gohma231** [comment]
How can I install an earlier version if I am not on 'The Forge'? I'm hosting locally.

**Comment by jopeek** [comment]
You have to extract the source code zip file from the link I put above into wherever your data\modules folder is.
