### ISSUE TITLE
UI scale too large

### ISSUE THREAD

**Issue by samuelrhaynes** [jopeek/fvtt-token-info-icons#38]
I have returned to using Foundry, just updated from 0.7 to 0.9 and then updated this module also, so this may well be an issue with my past user data.

However the UI for the token info is massive compared to the rest of the Foundy UI. Is there a way to make it all smaller?

![image](https://user-images.githubusercontent.com/8014292/161449469-82fb430a-8d6b-47ff-951f-ad74ae068eb0.png)

**Comment by jopeek** [comment]
Hmm weird, I’ve never seen that before and don’t get that in my game. Have you tried without any other modules?

**Comment by samuelrhaynes** [comment]
I'm a moron. I remembered "Find the culprit" and discovered I had Illandril's Token HUD Scaler installed. Sorry..
