### ISSUE TITLE
Forge Compatibility Warnings

### ISSUE THREAD

**Issue by MxViolette** [jopeek/fvtt-token-info-icons#42]
there are multiple compatibility warnings for this module when installing on Forge. The following is the output from my console log:

> [token-info-icons] The module "token-info-icons" is using "author" which is deprecated in favor of "authors"
> [token-info-icons] module "token-info-icons" contains "system" which is deprecated in favor of "relationships.systems"
> [token-info-icons] The module "token-info-icons" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object

**Comment by jopeek** [comment]
It uses both to maintain backwards compatibility. These warnings can be ignore/are faulty.
