### ISSUE TITLE
Update module for data model changes to resolve console warnings

### ISSUE THREAD

**Issue by Tregonia** [jopeek/fvtt-token-info-icons#43]
With v10, updates to the data model were implemented that result in numerous warning messages being displayed when opening a token. These messages are also displayed as compatibility warnings via the canvas as well.

Data model changes are explained here: [https://foundryvtt.com/article/v10-data-model/](https://foundryvtt.com/article/v10-data-model/)

<img width="1065" alt="Screen Shot 2023-03-10 at 10 37 34 PM" src="https://user-images.githubusercontent.com/1907677/224462953-0ca9a820-37fb-4b50-ae54-321431e838bc.png">

**Comment by jopeek** [comment]
Resolved in 2.3.10.
